### ISSUE TITLE
js.NewCallback and other errors in 12.X

### ISSUE THREAD

**Issue by davmaz** [stdiopt/gowasm-experiments#3]
These examples are incredible! There are some problems though when trying to build them:
**undefined: js.NewCallback** needs to be replaced with js.Func, but once that is done this happens:
**cannot convert func literal (type func([]js.Value)) to type js.Func**

Do you plan to update these? This is my first intro to wasm and it's a bit difficult to get through the errors...

**Comment by stdiopt** [comment]
Interesting, I'll try to update these to the latest go version and check what's going on

**Comment by stdiopt** [comment]
code updated, thanks for letting me know
