### ISSUE TITLE
No movement in image

### ISSUE THREAD

**Issue by davmaz** [stdiopt/gowasm-experiments#7]
Thanks for the great overview. However, if I follow the README.md, the code shows up in my browser (newest linux/Chrome) but the balls aren't there. 
go run ../serve.do shows Listening at :8080 and GET /bouncy/ but nothing is happening.

If I run it by surfing (same linux/Chrome) to your bouncy everything works!

What am I missing?

**Comment by stdiopt** [comment]
most likely because this repo ships pre-built wasm files with `wasm_exec.js` from go1.13 for demos to work in github. 
If you use a different go version to build you will need to update `wasm_exec.js` in each experiment

```bash
cd bouncy 
cp $GOROOT/misc/wasm/wasm_exec.js . # this will overwrite wasm_exec.js with your current go version one
./build.sh
go run ../serve.go
```

**Comment by davmaz** [comment]
That was definitely the issue. I updated wasm_exec.js in all the directories and it fixed it.
One thing that's got me puzzled is the source for the 'code background' -- the index.html seems to load it from main.go, but when I change main.go the background doesn't reflect the changes. Is it downloading it from another location? That's rhetorical obviously, but from where? Can I make it use the local main.go?

**Comment by stdiopt** [comment]
https://github.com/stdiopt/gowasm-experiments/blob/master/bouncy/index.html#L20 it is using the local main.go file, it might not be updating due to browser cache?

**Comment by davmaz** [comment]
That was exactly the cause. Thank you for all your help and the fantastic WASM examples!
